
- hosts: all
  tasks:
  - name: Print creating file
    debug: msg="Creating file in /root"
  - name: Creating a file with content
    copy:
      dest: "/root/ansible_sample_file.txt"
      content: |
        line 01
        line 02
